branch-defaults:
  ENTER:
    environment: null
  master:
    environment: null
    group_suffix: null
global:
  application_name: CompeTrackNew
  branch: ENTER
  default_ec2_keyname: asdf123
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: codecommit-origin2
  sc: git
  workspace_type: Application
